# Generated by Django 5.0.6 on 2024-05-07 23:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('A', 'aceito'), ('N', 'negado'), ('D', 'desligado')], max_length=1)),
                ('aceito', models.BooleanField(default=False)),
                ('user_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresa', to=settings.AUTH_USER_MODEL)),
                ('user_funcionario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='empregado', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
