# Generated by Django 5.0.6 on 2024-05-10 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0002_alter_funcionario_status_cargo'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='cargo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cargo_funcionario', to='empresa.cargo'),
            preserve_default=False,
        ),
    ]
